### ISSUE TITLE
Tree shaking implementation

### ISSUE THREAD

**Issue by acasazza** [commercelayer/commercelayer-react-components#210]
## Description
Try to implement "tree shaking" without using any bundle compiler.

## Tasks
- [x] Add `exports` to `package.json`
- [x] Add `typesVersions` to `package.json` (will be moved to `exports` soon)
- [x] Create `orders` folder to get components by `@commercelayer/react-components/orders` or `@commercelayer/react-components/orders/[component]`
- [x] Create `skus` folder to get components by `@commercelayer/react-components/skus` or `@commercelayer/react-components/skus/[component]`
